### ISSUE TITLE
trying example with Firebirdsql database

### ISSUE THREAD

**Issue by calhemp** [mybatis/generator#145]
Hil i'm trying to check how works with a firebird sql database.

i create a generatorConfig.xml with

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN" "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
<generatorConfiguration>
  <context id="context1">
    <jdbcConnection connectionURL="jdbc:firebirdsql://localhost:3050/database/FERRETERIAFACT.fdb" driverClass="org.firebirdsql.jdbc.FBDriver" password="masterkey" userId="sysdba" />
    <javaModelGenerator targetPackage="com.prova.ferreteria" targetProject="com.prova.ferreteriatarget" />
    <sqlMapGenerator targetPackage="com.prova.ferreteria.sql" targetProject="com.prova.ferreteriatarget.sql" />
    <javaClientGenerator targetPackage="com.prova.ferreteria.client" targetProject="com.prova.ferreteriatarget.client" type="XMLMAPPER" />
    <table schema="???" tableName="CLIENTES">
      <columnOverride column="???" property="???" />
    </table>
  </context>`

and command line

`java -cp ".;jaybird-2.2.11.jar;" -jar mybatis-generator-core-1.3.4.jar -configfile generatorConfig.xml`

but i get
`Exception in thread "main" java.lang.RuntimeException: Exception getting JDBC Driver
	at org.mybatis.generator.internal.JDBCConnectionFactory.getDriver(JDBCConnectionFactory.java:100)
	at org.mybatis.generator.internal.JDBCConnectionFactory.getConnection(JDBCConnectionFactory.java:70)
	at org.mybatis.generator.config.Context.getConnection(Context.java:753)
	at org.mybatis.generator.config.Context.introspectTables(Context.java:631)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:257)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:189)
	at org.mybatis.generator.api.ShellRunner.main(ShellRunner.java:117)
Caused by: java.lang.ClassNotFoundException: org.firebirdsql.jdbc.FBDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.mybatis.generator.internal.ObjectFactory.internalClassForName(ObjectFactory.java:181)
	at org.mybatis.generator.internal.ObjectFactory.externalClassForName(ObjectFactory.java:136)
	at org.mybatis.generator.internal.JDBCConnectionFactory.getDriver(JDBCConnectionFactory.java:97)
	... 6 more
`

the same with a eclipse project.

is firebird supported, or I'm missing something.

thanks

**Comment by jeffgbutler** [comment]
Couple of problems with this.

When you use java -jar, then the -cp option is ignored.  The other problem you will face is that firebird has a dependency on some JEE classes, so you should use the jaybird-full JAR.

So you need to change your command line to something like this:

```
java -cp jaybird-full-2.2.11.jar;mybatis-generator-core-1.3.4.jar; org.mybatis.generator.api.ShellRunner -configfile generatorConfig.xml
```
