### ISSUE TITLE
can not generate

### ISSUE THREAD

**Issue by jason19659** [mybatis/generator#146]
an error 
`/Users/jason/Documents/workspace/.metadata/.plugins/org.mybatis.generator.eclipse.ui/.generatedAntScripts/web-generatorConfig.xml.xml:4: Column name pattern can not be NULL or empty.
Column name pattern can not be NULL or empty.`
while using jdbc 5.1.23, and the xml like this,

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE generatorConfiguration PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN" "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd" >
<generatorConfiguration >
<classPathEntry location="/Users/jason/Downloads/generator/generator/need/mysql-connector-java-5.1.23-bin.jar" />
  <context id="DB2Tables" targetRuntime="MyBatis3">
    <jdbcConnection driverClass="com.mysql.jdbc.Driver" connectionURL="jdbc:mysql://localhost:3306/web" userId="root" password="root" />
    <javaModelGenerator targetPackage="a.model" targetProject="web" />
    <sqlMapGenerator targetPackage="a.mapper" targetProject="web" />
    <javaClientGenerator targetPackage="a.dao" targetProject="web" type="XMLMAPPER" />
        <table tableName="user_active" domainObjectName="UserActive" enableCountByExample="false" enableUpdateByExample="false" enableDeleteByExample="false" enableSelectByExample="false" selectByExampleQueryId="false" />
  </context>
</generatorConfiguration>
```

and the error change the while using jdbc 6.0.3.
```/Users/jason/Documents/workspace/.metadata/.plugins/org.mybatis.generator.eclipse.ui/.generatedAntScripts/web-generatorConfig.xml.xml:4: Column name pattern can not be NULL or empty.
Column name pattern can not be NULL or empty.```

create sql here,
```CREATE TABLE `user_active` (
  `id` char(36) NOT NULL DEFAULT '',
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  CONSTRAINT `user_active_ibfk_1` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;```
it works in old version 1.3.1.

**Comment by jeffgbutler** [comment]
I'm fairly certain this is due to a MySql connector-j change.  See this:

https://bugs.mysql.com/bug.php?id=81105

See if appending nullNamePatternMatchesAll=true to your connection string makes a difference.

**Comment by carlosacs** [comment]
Almost the same here, with Oracle, eplipse pluggin. The error message is "Invalid Column Name" (translated to pt_BR as "Nome de coluna inválido"). Just update from 1.3.2 to 1.3.4, no changes in configuration file.

Full stack trace:

java.sql.SQLException: Nome de coluna inválido
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:208)
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3319)
	at oracle.jdbc.driver.OracleResultSetImpl.findColumn(OracleResultSetImpl.java:1926)
	at oracle.jdbc.driver.OracleResultSet.getString(OracleResultSet.java:1515)
	at org.mybatis.generator.internal.db.DatabaseIntrospector.getColumns(DatabaseIntrospector.java:618)
	at org.mybatis.generator.internal.db.DatabaseIntrospector.introspectTables(DatabaseIntrospector.java:221)
	at org.mybatis.generator.config.Context.introspectTables(Context.java:653)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:257)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:189)
	at org.mybatis.generator.ant.GeneratorAntTask.execute(GeneratorAntTask.java:149)
	at Gen.main(Gen.java:20)

**Comment by jeffgbutler** [comment]
@carlosacs I believe you are experiencing #136, not this issue.
