### ISSUE TITLE
IS_GENERATEDCOLUMN error for sqlserver

### ISSUE THREAD

**Issue by beeant0512** [mybatis/generator#169]
com.microsoft.sqlserver.jdbc.SQLServerException: 列名 IS_GENERATEDCOLUMN 无效。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.findColumn(SQLServerResultSet.java:656)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getString(SQLServerResultSet.java:2401)
	at org.mybatis.generator.internal.db.DatabaseIntrospector.getColumns(DatabaseIntrospector.java:619)
	at org.mybatis.generator.internal.db.DatabaseIntrospector.introspectTables(DatabaseIntrospector.java:221)
	at org.mybatis.generator.config.Context.introspectTables(Context.java:649)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:254)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:138)

**Comment by jeffgbutler** [comment]
This is fixed in version 1.3.5.  Please upgrade.
