### ISSUE TITLE
The XmlElement cache-ref con‘t support  PluginAdapter extends

### ISSUE THREAD

**Issue by liyiorg** [mybatis/generator#290]
Hello,I want create a CacheRefPlugin. 
Question 1: MyBatis con’t add MBG comment in tag <cache-ref> 
```xml
<!-- error -->
<cache-ref namespace="example.mapper.AppLogMapper">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Thu Nov 09 11:33:25 CST 2017.
     -->
  </cache-ref>
```
Question 2: PluginAdapter extends and override method sqlMapDocumentGenerated.
```java
@Override
public boolean sqlMapDocumentGenerated(Document document, IntrospectedTable introspectedTable) {

	//Con't get tag cache-ref	
	for (Element element : document.getRootElement().getElements()) {				
		if (element instanceof XmlElement) {
			XmlElement tempElement = (XmlElement) element;
			if (tempElement.getName().equals("cache-ref")) {
				System.out.println("has tag cache-ref");		
			}
		}
	}
        return true;
}
```

**Comment by jeffgbutler** [comment]
I'm sorry - I don't understand your questions.

For Question 1, things look OK to me.

For Question 2, this method is where you would add the new element.

**Comment by liyiorg** [comment]
For Question 1
<cache-ref> con't add comment and  run error.  See  http://mybatis.org/dtd/mybatis-3-mapper.dtd
```log
org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 420; columnNumber: 8; 元素类型为 "cache-ref" 的内容必须匹配 "EMPTY"。不允许使用类型为 "comment" 的子级。
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:259)
	at org.apache.ibatis.parsing.XPathParser.<init>(XPathParser.java:125)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.<init>(XMLMapperBuilder.java:78)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.<init>(XMLMapperBuilder.java:73)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.loadXmlResource(MapperAnnotationBuilder.java:172)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:124)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:72)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:728)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:80)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
```

For Question 2
check exists tag <cache-ref>

**Comment by jeffgbutler** [comment]
Oh, I see.  The cache-ref element is marked as EMPTY in the MyBatis DTD, so you can't add a comment to it.  There's nothing the generator can do about that - it would need to be a change in MyBatis.  But I don't think that is likely, so it is best to not add comments to a generated cache-ref.  I realize this will cause problems with the XML merge, but there is no good solution for that.

For question 2, your code would only work if some other plugin had already added the cache-ref element.

**Comment by liyiorg** [comment]
Thanks,if no generator MBG comment,The MBG build new <cache-ref> xml element every time.

**Comment by jeffgbutler** [comment]
That is true.  But as I said, allowing this would require a change in the MyBatis DTD.

**Comment by jeffgbutler** [comment]
Nothing we can do about this in the generator.
