### ISSUE TITLE
Mysql 5.7+ version cannot be generated.

### ISSUE THREAD

**Issue by hncdyj123** [mybatis/generator#336]
hello，I found that I couldn't generate it when I was using the mysql5.7+ version.

**Comment by jeffgbutler** [comment]
We need more details to be able to help you.  Take a look at this page and see if it helps: http://www.mybatis.org/generator/usage/mysql.html

**Comment by Centaur** [comment]
Not sure it is the same problem the op encountered, but when generating for "MyBatis3DynamicSql" from mysql 5.7.21 I got this

```
Exception in thread "main" java.lang.NullPointerException
	at org.mybatis.generator.api.dom.java.FullyQualifiedJavaType.parse(FullyQualifiedJavaType.java:353)
	at org.mybatis.generator.api.dom.java.FullyQualifiedJavaType.<init>(FullyQualifiedJavaType.java:83)
	at org.mybatis.generator.runtime.dynamic.sql.DynamicSqlMapperGenerator.createBasicInterface(DynamicSqlMapperGenerator.java:129)
	at org.mybatis.generator.runtime.dynamic.sql.DynamicSqlMapperGenerator.getCompilationUnits(DynamicSqlMapperGenerator.java:81)
	at org.mybatis.generator.codegen.mybatis3.IntrospectedTableMyBatis3Impl.getGeneratedJavaFiles(IntrospectedTableMyBatis3Impl.java:190)
	at org.mybatis.generator.config.Context.generateFiles(Context.java:517)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:269)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:139)
```

I have minimized my table to 
```sql
CREATE TABLE Person (
  id          INT AUTO_INCREMENT PRIMARY KEY
)
```
still no luck.

I am running kotlin with a java based configuration.

**Comment by jeffgbutler** [comment]
Thanks!  I’ll take a look.

**Comment by jeffgbutler** [comment]
Can you tell me the version of connector/j you are using?

**Comment by hncdyj123** [comment]
sorry,I used version 1.3.3, and now I use version 1.3.6, ok.But there will be warnings, mysql version: 5.7.21, jdbcdiver: 5.1.45.
Warn the log:
The 2018-04-04 09:05:39. 956. [the main] the DEBUG O.M.G.I.D b.D atabaseIntrospector - Retrieving column information for the table "city"
The 2018-04-04 09:05:40. 013. [the main] the DEBUG O.M.G.I.D b.D atabaseIntrospector - Found the column "city_id", data type, 4 in the table "hlyg - db..City"
CREATE TABLE `city` (
  `city_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `city_no` varchar(50) DEFAULT NULL COMMENT '城市编码',
  `city_name` varchar(50) DEFAULT NULL COMMENT '城市名称',
  `city_short` varchar(50) DEFAULT NULL COMMENT '城市简称',
  `is_use` int(11) DEFAULT NULL COMMENT '是否使用，0：未使用，1：已使用',
  `province_id` int(11) DEFAULT NULL COMMENT '省份主键',
  `area_no` varchar(20) DEFAULT NULL COMMENT '区号',
  PRIMARY KEY (`city_id`)
) ENGINE=InnoDB AUTO_INCREMENT=329 DEFAULT CHARSET=utf8 COMMENT='城市表';

**Comment by Centaur** [comment]
@jeffgbutler `mysql:mysql-connector-java:5.1.46`

**Comment by Centaur** [comment]
Turns out that my exception was caused by not providing `javaClientGenerator` part. Seems this part is required for `Mybatis3DynamicSql` runtimeTarget. This can be mentioned in the document.

**Comment by jeffgbutler** [comment]
Thanks for reporting back.  I'll see if I can add a validation for that.
