### ISSUE TITLE
bug:java.lang.ClassCastException at selectOne method

### ISSUE THREAD

**Issue by 411937647** [mybatis/generator#531]
Version is 1.4.0.
Mybatis-dynamic-sql version is 1.1.4.
Mybatis version is 3.4.6.
generate code like this 
  ```
   @SelectProvider(type = SqlProviderAdapter.class, method = "select")
    @ResultMap("DepartInfoResult")
    Optional<DepartInfo> selectOne(SelectStatementProvider selectStatement);

    default Optional<DepartInfo> selectOne(SelectDSLCompleter completer) {
        return MyBatis3Utils.selectOne(this::selectOne, selectList, departInfoEntity, completer);
    }
```
And i use selectOne method like this
`mapper.selectOne(c->c.where(id,isEqualTo(999)));`
Here is the stackTrace:

> java.lang.ClassCastException: com.hst.ces.entity.DepartInfo cannot be cast to java.util.Optional
> 	at com.sun.proxy.$Proxy62.selectOne(Unknown Source)
> 	at org.mybatis.dynamic.sql.util.mybatis3.MyBatis3Utils.selectOne(MyBatis3Utils.java:142)
> 	at com.hst.ces.mybatis.mybatis3.dao.IDepartInfoMapper.selectOne(IDepartInfoMapper.java:132)

**Comment by 411937647** [comment]
I make a mistake.Optional is support since mybatis 3.5 and later.
