### ISSUE TITLE
ReflectionException due to missing annotation for Primary Key

### ISSUE THREAD

**Issue by bzhou003** [mybatis/generator#559]
The problem is on these two methods generated in my UserMapper.java
```
int deleteByPrimaryKey(Long id);
User selectByPrimaryKey(Long id);
```

If I manually add @Param annotation, it will work fine, otherwise it will throw the following error:
```
Exception in thread "main" org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'id' in 'class java.lang.Long'
### Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'id' in 'class java.lang.Long'
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93)
	at com.sun.proxy.$Proxy21.selectByPrimaryKey(Unknown Source)
	at com.venmo.rdbms.example.UserOperationExample.readOperation(UserOperationExample.java:132)
	at com.venmo.rdbms.example.UserOperationExample.readFromMaster_aroundBody12(UserOperationExample.java:119)
	at com.venmo.rdbms.example.UserOperationExample$AjcClosure13.run(UserOperationExample.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.venmo.rdbms.core.aop.CustomDataSourceAspect.changeDataSource(CustomDataSourceAspect.java:32)
	at com.venmo.rdbms.example.UserOperationExample.readFromMaster(UserOperationExample.java:118)
	at com.venmo.rdbms.example.UserOperationExample.readFromMaster_aroundBody4(UserOperationExample.java:44)
	at com.venmo.rdbms.example.UserOperationExample$AjcClosure5.run(UserOperationExample.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.venmo.rdbms.core.aop.CustomDataSourceAspect.changeDataSource(CustomDataSourceAspect.java:32)
	at com.venmo.rdbms.example.UserOperationExample.main(UserOperationExample.java:44)
Caused by: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'id' in 'class java.lang.Long'
Caused by: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'id' in 'class java.lang.Long'

	at org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:373)
	at org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:163)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:162)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
	at com.venmo.rdbms.core.interceptor.ReadWriteDistinguishInterceptor.intercept(ReadWriteDistinguishInterceptor.java:63)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy20.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 16 more
```

I tried to generate my own BaseMapper, similar to the process here: https://www.lagou.com/lgeduarticle/71255.html
But I cannot give Param annotation value for the general type.

Do you have any suggestions how to solve the problem without manual change? Thanks.

**Comment by jeffgbutler** [comment]
With MyBatis, you don't need to use `@Param` if there is just a single value on the method. So I'm assuming that something in your BaseMapper is interfering with the normal behavior. My best guess is that the base mapper is assuming there is an object in the select by primary key methods, rather than a single value. You can force the generator to create such an object if you set the model type to hierarchical like this:

```xml
<context defaultModelType="hierarchical" ...>
  ...
</context>
```

**Comment by bzhou003** [comment]
Hi @jeffgbutler, your suggestion works, thank you so much for the quick response.
