### ISSUE TITLE
two same @Results was generated

### ISSUE THREAD

**Issue by ptxl** [mybatis/generator#667]
generatorConfig.xml file content

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration PUBLIC
        "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
<generatorConfiguration>
    <context id="context1" >
        <commentGenerator>
             <property name="suppressAllComments" value="true" />
        </commentGenerator>
        <jdbcConnection connectionURL="jdbc:mysql://localhost/test" driverClass="com.mysql.jdbc.Driver"
            password="tiger" userId="root" />
        <javaModelGenerator targetPackage="com.generator.bean" targetProject="src/main/java" />
        <sqlMapGenerator targetPackage="generator" targetProject="src/main/resources" />
        <javaClientGenerator targetPackage="com.generator.dao" targetProject="src/main/java" type="XMLMAPPER" />
        <table tableName="film">
        </table>
    </context>
</generatorConfiguration>
```

FilmMapper.java
```java
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    @SelectProvider(type=SqlProviderAdapter.class, method="select")
    @Results(id="FilmResult", value = {
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    Optional<Film> selectOne(SelectStatementProvider selectStatement);`

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    @SelectProvider(type=SqlProviderAdapter.class, method="select")
    @Results(id="FilmResult", value = {
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<Film> selectMany(SelectStatementProvider selectStatement);
```

two Results'id are same,id is FilmResult，the following is exception stack

```
Exception in thread "main" java.lang.IllegalArgumentException: Result Maps collection already contains value for com.generator.dao.FilmMapper.FilmResult
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:1014)
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:970)
	at org.apache.ibatis.session.Configuration.addResultMap(Configuration.java:726)
	at org.apache.ibatis.builder.MapperBuilderAssistant.addResultMap(MapperBuilderAssistant.java:209)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.applyResultMap(MapperAnnotationBuilder.java:258)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parseResultMap(MapperAnnotationBuilder.java:232)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:129)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:72)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:841)
	at com.juggernaut.mybatis.demo.MybatisAnnotationDemo.main(MybatisAnnotationDemo.java:30)
```

**Comment by jeffgbutler** [comment]
I believe this is resolved in the current snapshot version. Are you able to try version 1.4.1-SNAPSHOT and let us know?

Snapshot builds are available here: https://oss.sonatype.org/content/repositories/snapshots

**Comment by ptxl** [comment]
> I believe this is resolved in the current snapshot version. Are you able to try version 1.4.1-SNAPSHOT and let us know?
> 
> Snapshot builds are available here: https://oss.sonatype.org/content/repositories/snapshots

thanks, that's work.
