### ISSUE TITLE
Eclipse MARS SR2 fails to load MyBatis generator plugin

### ISSUE THREAD

**Issue by dbamk** [mybatis/generator#84]
Attempting to install the MyBatis generator Eclipse plugin to a fresh copy of Eclipse MARS SR2 is failing with the following error symptom:

Unable to read repository at file:/C:/Dev/_/eclipse/p2/org.eclipse.equinox.p2.repository/cache/content603936354.xml. Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.

This plugin worked fine with Eclipse Mars SR1 (and earlier versions of Eclipse such as Kepler and Luna), but was previously hosted at http://mybatis.googlecode.com/svn/sub-projects/generator/trunk/eclipse/UpdateSite/ which no longer exists.

I have not found any [relevant] help on the web that explains what might be wrong ... here is what I did:

    Unzip eclipse-jee-mars-2-win32-x86_64.zip (MD5 = 686f0c8dfa1aab53fa13e50aacd84a4a)
    Update the eclipse.ini file for Java 8u92
    Start Eclipse
    Open Help --> Install New Software --> Add (site) ... with an Eclipse Update Site URL of https://github.com/mybatis/generator/tree/master/eclipse/UpdateSite/ ... click OK
    Error encountered and update site not reached. The XML file appears to be HTML with two occurrences of the malformed "meta" element in the <head> portion of the document. (This website won't let me attached the malformed file!).

The following session data is applicable:

    eclipse.buildId=4.5.2.M20160212-1500
    java.version=1.8.0_92
    java.vendor=Oracle Corporation
    BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_CA
    Framework arguments:  -product org.eclipse.epp.package.jee.product
    Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

Detailed event error log information has this stack dump:

java.io.IOException: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryIO$Parser.parse(MetadataRepositoryIO.java:215)
at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryIO.read(MetadataRepositoryIO.java:63)
at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:107)
at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:339)
at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:146)
at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:389)
at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
at org.eclipse.equinox.p2.ui.ProvisioningUI.loadMetadataRepository(ProvisioningUI.java:440)
at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.getMetadataRepository(MetadataRepositoryElement.java:126)
at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.getRepository(MetadataRepositoryElement.java:115)
at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.getQueryable(MetadataRepositoryElement.java:109)
at org.eclipse.equinox.internal.p2.ui.QueryProvider.getQueryDescriptor(QueryProvider.java:88)
at org.eclipse.equinox.internal.p2.ui.model.QueriedElement.fetchChildren(QueriedElement.java:101)
at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.fetchChildren(MetadataRepositoryElement.java:77)
at org.eclipse.equinox.internal.p2.ui.model.RemoteQueriedElement.fetchDeferredChildren(RemoteQueriedElement.java:34)
at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:232)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by jeffgbutler** [comment]
Well the Google code site finally went away.  I'll have to get this moved to bintray.  I'll post here when that is complete.

**Comment by dbamk** [comment]
Any idea when this is going to get addressed? I would like to upgrade my dev env to the latest stable Eclipse release, and Neon will be rolling out before too long ...

**Comment by jeffgbutler** [comment]
The new release is now available.  The eclipse update site is here:

https://dl.bintray.com/mybatis/mybatis-generator/
