### ISSUE TITLE
GeneratedJavaFile.java bug

### ISSUE THREAD

**Issue by beeant0512** [mybatis/generator#97]
when a write a plugin( extend PluginAdapter), i` @Override contextGenerateAdditionalJavaFiles(IntrospectedTable introspectedTable) `method, and i wrote thess codes:
```
superServiceInterfaceFqjt = new FullyQualifiedJavaType(superService);
superServiceInterfaceFqjt.addTypeArgument(new FullyQualifiedJavaType("T"));

Interface interfaze = new Interface(superServiceInterfaceFqjt);

GeneratedJavaFile javaFile = new GeneratedJavaFile(interfaze, context.getJavaModelGeneratorConfiguration()
                .getTargetProject(),
                context.getProperty(PropertyRegistry.CONTEXT_JAVA_FILE_ENCODING),
                context.getJavaFormatter());
```

when i run the code
~~~
java.io.FileNotFoundException: H:\javaweb\angular\src\main\java\com\beeant\common\service\IBaseService<T>.java (文件名、目录名或卷标语法不正确。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.mybatis.generator.api.MyBatisGenerator.writeFile(MyBatisGenerator.java:381)
	at org.mybatis.generator.api.MyBatisGenerator.writeGeneratedJavaFile(MyBatisGenerator.java:326)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:282)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:138)
	at StartUp.main(StartUp.java:29)
~~~

in GeneratedJavaFile.java , i thought it is an bug to get the filename when a interface have argetments
~~~
@Override
    public String getFileName() {
        return compilationUnit.getType().getShortName() + ".java"; //$NON-NLS-1$
    }
~~~
here is what i Override
~~~
String fulllyQualifiedNameWithoutTypeParameterts = compilationUnit.getType().getFullyQualifiedNameWithoutTypeParameters();
        FullyQualifiedJavaType fullyQualifiedJavaType = new FullyQualifiedJavaType(fulllyQualifiedNameWithoutTypeParameterts);
        return fullyQualifiedJavaType.getShortName() + ".java"; //$NON-NLS-1$
~~~

**Comment by jeffgbutler** [comment]
Good catch. Thanks for reporting this!
